import { check, connect, disconnect, startServer, day, finish } from '../lib.mjs';
import mongoose from 'mongoose';
import crypto from 'crypto';
import User from '../../src/models/User.js';
import Loan from '../../src/models/Loan.js';
import EMIPayment from '../../src/models/EMIPayment.js';
import AuditLog from '../../src/models/AuditLog.js';
import AmlAlert from '../../src/models/AmlAlert.js';
import Notification from '../../src/models/Notification.js';
import AgreementAcceptance from '../../src/models/AgreementAcceptance.js';
import { generateToken } from '../../src/middleware/auth.js';

const DB = 'fintech-test-compliance';
await connect(DB);
const srv = await startServer(DB);
const B = srv.base;

const bank = (n, acct = `10000000${n}`) => ({ accountNumber: acct, ifscCode: 'SBIN0001234', accountHolder: `User${n}`, bankName: 'SBI' });
const mk = (first, last, i, extra = {}) => User.create({ firstName: first, lastName: last, email: `u${i}@x.in`, phone: `98000000${10 + i}`, password: 'x12345678', bankAccount: bank(i), ...extra });
const adminUser = await User.create({ firstName: 'Ad', lastName: 'Min', email: 'admin@lifc.in', phone: '9800000001', password: 'AdminPass123' });
const A = await mk('Asha', 'Rao', 1), Bk = await mk('Bhanu', 'Iyer', 2), C = await mk('Chitra', 'Das', 3), D = await mk('Dev', 'Nair', 4), E = await mk('Esha', 'Pal', 5);
const tok = u => generateToken(String(u._id), u.email);
const admin = generateToken(String(adminUser._id), 'admin@lifc.in', true);

const call = async (m, p, t = admin, body, headers = {}) => {
  const r = await fetch(B + p, { method: m, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${t}`, ...headers }, body: ['POST', 'PUT', 'DELETE'].includes(m) && body !== undefined ? JSON.stringify(body) : (m === 'POST' ? '{}' : undefined) });
  const text = await r.text(); let d; try { d = JSON.parse(text); } catch { d = text; }
  return { s: r.status, d };
};
const audits = async q => (await call('GET', '/admin/compliance/audit?limit=200' + (q || ''))).d;
const hasAudit = async (action, pred = () => true) => (await audits('&action=' + action)).entries.some(pred);

console.log('ACCOUNT STATUS');
check('active customer can call customer route', (await call('GET', '/notifications', tok(A))).s === 200);
check('token with non-user id -> 401', (await call('GET', '/notifications', generateToken('someoneelse', 'o@x.in'))).s === 401);
await User.updateOne({ _id: E._id }, { status: 'blocked' });
check('blocked customer -> 403', (await call('GET', '/notifications', tok(E))).s === 403);
await User.updateOne({ _id: E._id }, { status: 'active' });

console.log('KYC');
check('bad PAN format -> 400', (await call('PUT', '/users/profile', tok(A), { panNumber: 'ABCDE1234' })).s === 400);
check('PAN with invalid holder type (4th char Z) -> 400', (await call('PUT', '/users/profile', tok(A), { panNumber: 'ABCZE1234F' })).s === 400);
const put = await call('PUT', '/users/profile', tok(A), { panNumber: 'abcpe1234f' });
check('profile PAN saved', put.s === 200, JSON.stringify(put.d).slice(0, 150));
let ua = await User.findById(A._id);
check('customer CANNOT self-approve KYC (stays pending)', ua.panNumber === 'ABCPE1234F' && ua.kycStatus === 'pending', ua.kycStatus);
const dup = await call('PUT', '/users/profile', tok(Bk), { panNumber: 'ABCPE1234F' });
check('duplicate PAN refused (409)', dup.s === 409, dup.s);
check('duplicate PAN raised HIGH AML alert for the second user', !!(await AmlAlert.findOne({ rule: 'DUPLICATE_PAN', userId: Bk._id, severity: 'HIGH' })));
const kp = await call('POST', '/kyc/pan', tok(A), { panNumber: 'ABCPE1234F' });
check('/kyc/pan without a provider -> not verified, pending review', kp.s === 200 && kp.d.verified === false && kp.d.mode === 'manual_review' && kp.d.kycStatus === 'pending', JSON.stringify(kp.d));
const q = (await call('GET', '/admin/compliance/kyc')).d;
check('admin KYC queue lists the pending customer', q.items.length === 1 && q.items[0].pan === 'ABCPE1234F' && q.items[0].bank.account.startsWith('XXXX'), JSON.stringify(q).slice(0, 200));
check('reject needs a reason', (await call('POST', `/admin/compliance/kyc/${A._id}/decision`, admin, { decision: 'reject' })).s === 400);
check('bad decision -> 400', (await call('POST', `/admin/compliance/kyc/${A._id}/decision`, admin, { decision: 'maybe' })).s === 400);
check('customer cannot use admin compliance (403)', (await call('GET', '/admin/compliance/kyc', tok(A))).s === 403);
check('admin approves KYC', (await call('POST', `/admin/compliance/kyc/${A._id}/decision`, admin, { decision: 'approve' })).s === 200 && (await User.findById(A._id)).kycStatus === 'approved');
check('re-submitting the same approved PAN keeps approval', (await call('POST', '/kyc/pan', tok(A), { panNumber: 'ABCPE1234F' })).d.kycStatus === 'approved');
check('KYC decision audited', await hasAudit('KYC_DECISION', e => e.details.decision === 'approve' && e.actor === 'admin@lifc.in'));

console.log('AML RULES (at application)');
const apply = (u, amount = 50000) => call('POST', '/loans/apply', tok(u), { loanAmount: amount, tenure: 6, purpose: 'Personal' });
const la = await apply(A, 250000);
check('application accepted', la.s === 201, JSON.stringify(la.d).slice(0, 150));
const loanA = await Loan.findOne({ userId: A._id });
check('LARGE_LOAN (MEDIUM) raised for 2.5L', !!(await AmlAlert.findOne({ rule: 'LARGE_LOAN', loanId: loanA._id, severity: 'MEDIUM' })));
check('application audited', await hasAudit('LOAN_APPLIED', e => e.entityId === String(loanA._id)));
await apply(C); await apply(C); await apply(C);
check('RAPID_REAPPLICATION raised on 3rd application in 24h', !!(await AmlAlert.findOne({ rule: 'RAPID_REAPPLICATION', userId: C._id })));
await User.updateOne({ _id: Bk._id }, { 'bankAccount.accountNumber': A.bankAccount.accountNumber });
await apply(Bk, 40000);
check('SHARED_BANK_ACCOUNT (HIGH) raised', !!(await AmlAlert.findOne({ rule: 'SHARED_BANK_ACCOUNT', userId: Bk._id, severity: 'HIGH' })));
const wl = await call('POST', '/admin/compliance/aml/watchlist', admin, { name: 'DEV NAIR', source: 'Internal', reason: 'Test entry' });
check('watchlist entry added and existing customer matched (name, any order/case)', wl.s === 201 && wl.d.existingCustomersMatched === 1, JSON.stringify(wl.d).slice(0, 200));
check('watchlist alert raised for existing customer', !!(await AmlAlert.findOne({ rule: 'WATCHLIST_MATCH', userId: D._id })));
await apply(D, 30000);
check('no duplicate open WATCHLIST alert on application (same loan-less alert + loan alert allowed, but one per rule/loan)', (await AmlAlert.countDocuments({ rule: 'WATCHLIST_MATCH', userId: D._id, status: 'OPEN' })) <= 2);
check('watchlist needs an identifier', (await call('POST', '/admin/compliance/aml/watchlist', admin, { source: 'x' })).s === 400);
check('watchlist rejects bad PAN', (await call('POST', '/admin/compliance/aml/watchlist', admin, { pan: 'BAD' })).s === 400);

console.log('APPROVAL GATES');
const loanD = await Loan.findOne({ userId: D._id });
let r = await call('POST', `/admin/loans/${loanD._id}/approve`);
check('KYC not approved -> approval blocked (409)', r.s === 409 && /KYC/.test(r.d.error), JSON.stringify(r.d));
await User.updateOne({ _id: D._id }, { kycStatus: 'approved', panNumber: 'DEVPN1234N' });
r = await call('POST', `/admin/loans/${loanD._id}/approve`);
check('open HIGH AML alert -> approval blocked (409)', r.s === 409 && /AML/.test(r.d.error), JSON.stringify(r.d));
r = await call('POST', `/admin/loans/${loanA._id}/approve`);
check('KYC ok + only MEDIUM alert -> approval allowed', r.s === 200, JSON.stringify(r.d));
check('approval audited', await hasAudit('LOAN_APPROVED', e => e.entityId === String(loanA._id)));

console.log('AGREEMENT');
const loanB = await Loan.findOne({ userId: Bk._id });
check('agreement not available before approval', (await call('GET', `/compliance/agreement/${loanB._id}`, tok(Bk))).s === 400);
const ag = await call('GET', `/compliance/agreement/${loanA._id}`, tok(A));
check('agreement text + hash for approved loan', ag.s === 200 && ag.d.text.includes('LOAN AGREEMENT') && ag.d.text.includes('Rs 2,50,000') && ag.d.accepted === null, JSON.stringify(ag.d).slice(0, 120));
check('hash is sha256 of the text', ag.d.hash === crypto.createHash('sha256').update(ag.d.text).digest('hex'));
check("another customer cannot read it (404)", (await call('GET', `/compliance/agreement/${loanA._id}`, tok(C))).s === 404);
check('disburse BEFORE acceptance blocked (409)', (await call('POST', `/admin/loans/${loanA._id}/disburse`)).s === 409);
check('payments route also blocked (409)', (await call('POST', `/payments/disburse/${loanA._id}`)).s === 409);
check('accept needs confirmed:true', (await call('POST', `/compliance/agreement/${loanA._id}/accept`, tok(A), { hash: ag.d.hash })).s === 400);
check('accept with wrong hash -> 409', (await call('POST', `/compliance/agreement/${loanA._id}/accept`, tok(A), { confirmed: true, hash: 'deadbeef' })).s === 409);
const acc = await call('POST', `/compliance/agreement/${loanA._id}/accept`, tok(A), { confirmed: true, hash: ag.d.hash }, { 'x-forwarded-for': '198.51.100.7, 203.0.113.9', 'user-agent': 'TestApp/1.0' });
check('agreement accepted', acc.s === 200, JSON.stringify(acc.d));
const rec = await AgreementAcceptance.findOne({ loanId: loanA._id });
check('forged left-most X-Forwarded-For is ignored; proxy-appended IP recorded',rec && rec.ip === '203.0.113.9',rec && rec.ip);
check('acceptance evidence stored (hash, text, ip, user agent)', rec && rec.hash === ag.d.hash && rec.text === ag.d.text && rec.ip === '203.0.113.9' && rec.userAgent === 'TestApp/1.0', JSON.stringify(rec));
check('second accept is idempotent', (await call('POST', `/compliance/agreement/${loanA._id}/accept`, tok(A), { confirmed: true, hash: ag.d.hash })).d.alreadyAccepted === true && (await AgreementAcceptance.countDocuments({ loanId: loanA._id })) === 1);
check('acceptance audited with ip', await hasAudit('AGREEMENT_ACCEPTED', e => e.entityId === String(loanA._id) && e.ip === '203.0.113.9'));
r = await call('POST', `/admin/loans/${loanA._id}/disburse`);
check('disburse AFTER acceptance works', r.s === 200 && (await Loan.findById(loanA._id)).status === 'disbursed', JSON.stringify(r.d));
check('disbursement audited', await hasAudit('LOAN_DISBURSED', e => e.entityId === String(loanA._id)));

console.log('AML REVIEW');
const open = (await call('GET', '/admin/compliance/aml/alerts?status=OPEN')).d;
check('open alerts listed with counts', open.items.length >= 5 && open.counts.OPEN === open.items.length, JSON.stringify(open.counts));
const hi = open.items.find(a => a.severity === 'HIGH');
check('review needs a note', (await call('POST', `/admin/compliance/aml/alerts/${hi.id}`, admin, { status: 'CLEARED' })).s === 400);
check('bad status -> 400', (await call('POST', `/admin/compliance/aml/alerts/${hi.id}`, admin, { status: 'OPEN', note: 'x' })).s === 400);
check('escalate', (await call('POST', `/admin/compliance/aml/alerts/${hi.id}`, admin, { status: 'ESCALATED', note: 'Needs MLRO review' })).s === 200);
check('cannot escalate twice', (await call('POST', `/admin/compliance/aml/alerts/${hi.id}`, admin, { status: 'ESCALATED', note: 'again' })).s === 409);
check('escalated alert can be cleared', (await call('POST', `/admin/compliance/aml/alerts/${hi.id}`, admin, { status: 'CLEARED', note: 'False positive' })).s === 200);
for (const a of (await AmlAlert.find({ status: 'OPEN', severity: 'HIGH' }))) await call('POST', `/admin/compliance/aml/alerts/${a._id}`, admin, { status: 'CLEARED', note: 'Reviewed, genuine customer' });
await User.updateOne({ _id: Bk._id }, { kycStatus: 'approved', panNumber: 'BHAPN1234B' });
check('after alerts cleared, the blocked loan can be approved', (await call('POST', `/admin/loans/${loanB._id}/approve`)).s === 200);
check('alert review audited', await hasAudit('AML_ALERT_REVIEWED'));
check('watchlist removal works and is audited', (await call('DELETE', `/admin/compliance/aml/watchlist/${wl.d.entry._id}`)).s === 200 && await hasAudit('WATCHLIST_REMOVED'));

console.log('EARLY-CLOSURE RULE');
const fl = await Loan.create({ userId: E._id, loanAmount: 24000, tenure: 3, interestRate: 15, monthlyEMI: 10000, status: 'disbursed', disbursementDate: day(-5), disbursedAmount: 24000 });
for (const [n, d] of [[1, 25], [2, 55], [3, 85]]) await EMIPayment.create({ loanId: fl._id, userId: E._id, emiNumber: n, dueDate: day(d), amount: 10000, principalAmount: 8000, interestAmount: 2000, status: 'PENDING' });
const quote = await call('GET', `/emi/foreclosure/${fl._id}`, tok(E));
const done = await call('POST', `/emi/foreclosure/${fl._id}`, tok(E), { expectedAmount: quote.d.total });
check('foreclosure within 30 days succeeds', done.s === 200, JSON.stringify(done.d).slice(0, 150));
check('EARLY_CLOSURE alert raised', !!(await AmlAlert.findOne({ rule: 'EARLY_CLOSURE', loanId: fl._id })));
check('foreclosure audited', await hasAudit('LOAN_FORECLOSED', e => e.entityId === String(fl._id)));

console.log('LEGACY ADMIN ROUTES');
check('legacy route cannot set disbursed', (await call('PUT', `/admin/loans/${loanD._id}/status`, admin, { status: 'disbursed' })).s === 400);
check('legacy route cannot set approved', (await call('PUT', `/admin/loans/${loanD._id}/status`, admin, { status: 'approved' })).s === 400);
check('legacy route can still set under_review (audited)', (await call('PUT', `/admin/loans/${loanD._id}/status`, admin, { status: 'under_review' })).s === 200 && await hasAudit('LOAN_STATUS_CHANGED'));

console.log('CONFIG + LOGIN AUDIT');
await call('PUT', '/admin/config', admin, { keys: { SMS_API_KEY: 'super-secret-value-123' } });
const cfgAudit = (await audits('&action=CONFIG_UPDATED')).entries;
check('config change audited with key names', cfgAudit.length === 1 && cfgAudit[0].details.keys.includes('SMS_API_KEY'));
check('config SECRET VALUE is NOT in the audit log', !JSON.stringify(await audits()).includes('super-secret-value-123'));
const lg = await fetch(B + '/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'admin@lifc.in', password: 'AdminPass123' }) });
check('admin login works', lg.status === 200);
check('admin login audited', await hasAudit('ADMIN_LOGIN'));

console.log('DATA RIGHTS');
const exp = await call('GET', '/compliance/my-data', tok(A));
check('export has profile, loans, agreements; no password', exp.s === 200 && exp.d.profile.firstName === 'Asha' && !('password' in exp.d.profile) && exp.d.loans.length === 1 && exp.d.agreements.length === 1, JSON.stringify(Object.keys(exp.d)));
check('export audited', await hasAudit('DATA_EXPORTED'));
const dr = await call('POST', '/compliance/deletion-request', tok(A), { reason: 'Leaving' });
check('deletion request created', dr.s === 201);
check('second open request -> 409', (await call('POST', '/compliance/deletion-request', tok(A), {})).s === 409);
const reqs = (await call('GET', '/admin/compliance/requests')).d;
check('admin sees the request with active-loan count', reqs.items.length === 1 && reqs.items[0].activeLoans >= 1, JSON.stringify(reqs.items[0]));
const rid = reqs.items[0].id;
check('deletion BLOCKED while loan is active (409)', (await call('POST', `/admin/compliance/requests/${rid}/process`, admin, { action: 'complete' })).s === 409);
check('reject needs a reason', (await call('POST', `/admin/compliance/requests/${rid}/process`, admin, { action: 'reject' })).s === 400);
// Settle E (closed loan) and process E's deletion
await Notification.create({ userId: E._id, type: 'EMI_PAID', title: 't', message: 'm' });
const dre = await call('POST', '/compliance/deletion-request', tok(E), {});
const reqE = (await call('GET', '/admin/compliance/requests')).d.items.find(i => i.email === E.email);
check("E's loan is closed so no blockers", reqE && reqE.activeLoans === 0);
const proc = await call('POST', `/admin/compliance/requests/${reqE.id}/process`, admin, { action: 'complete', note: 'Verified identity' });
check('deletion completed', proc.s === 200, JSON.stringify(proc.d));
const ue = await User.findById(E._id).lean();
check('personal data removed', ue.firstName === 'Deleted' && ue.email.endsWith('@deleted.invalid') && ue.phone.startsWith('del-') && !ue.panNumber && !ue.bankAccount && !ue.address && ue.status === 'inactive', JSON.stringify(ue).slice(0, 300));
check('notifications deleted', (await Notification.countDocuments({ userId: E._id })) === 0);
check('loan + EMI records RETAINED', (await Loan.countDocuments({ userId: E._id })) === 1 && (await EMIPayment.countDocuments({ userId: E._id })) === 3);
check('deleted customer cannot log in with old token (403)', (await call('GET', '/notifications', tok(E))).s === 403);
check('anonymization audited', await hasAudit('USER_ANONYMIZED', e => e.entityId === String(E._id)));
check('request marked completed', (await call('GET', '/admin/compliance/requests?status=COMPLETED')).d.items.length === 1);

console.log('AUDIT LOG INTEGRITY');
const n0 = await AuditLog.countDocuments();
await Promise.all(Array.from({ length: 30 }, () => call('GET', '/compliance/my-data', tok(A))));
const n1 = await AuditLog.countDocuments();
check('NO audit entry lost under 30 concurrent writers', n1 === n0 + 30, `${n0} -> ${n1}`);
const v1 = (await call('GET', '/admin/compliance/audit/verify')).d;
check('chain valid after concurrent writers', v1.ok === true && v1.checked === n1, JSON.stringify(v1));
const seqs = (await AuditLog.find().select('seq').lean()).map(x => x.seq).sort((a, b) => a - b);
check('sequence numbers unique and gapless', seqs.every((s, i) => s === i + 1), `${seqs.length} entries`);
check('API cannot rewrite entries (mongoose update blocked)', await AuditLog.updateOne({ seq: 1 }, { actor: 'x' }).then(() => false, () => true));
check('API cannot delete entries', await AuditLog.deleteMany({}).then(() => false, () => true));
const list = (await call('GET', '/admin/compliance/audit?action=LOAN_APPROVED')).d;
check('audit filter by action', list.total >= 2 && list.entries.every(e => e.action === 'LOAN_APPROVED'));
const exp2 = await fetch(B + '/admin/compliance/audit/export', { headers: { Authorization: `Bearer ${admin}` } });
const csv = await exp2.text();
check('audit CSV export', exp2.status === 200 && csv.startsWith('"Seq","Time (UTC)"') && csv.split('\r\n').length > 60);
check('bad date filter -> 400', (await call('GET', '/admin/compliance/audit?from=garbage')).s === 400);
// Tamper directly in the database, bypassing the app, and make sure verification catches it.
const col = mongoose.connection.collection('auditlogs');
const target = await col.findOne({ seq: 10 });
await col.updateOne({ seq: 10 }, { $set: { actor: 'attacker@evil.test' } });
const v2 = (await call('GET', '/admin/compliance/audit/verify')).d;
check('EDITED entry detected', v2.ok === false && v2.brokenAt === 10 && /hash/.test(v2.reason), JSON.stringify(v2));
await col.updateOne({ seq: 10 }, { $set: { actor: target.actor } });
check('chain valid again once restored', (await call('GET', '/admin/compliance/audit/verify')).d.ok === true);
await col.deleteOne({ seq: 20 });
const v3 = (await call('GET', '/admin/compliance/audit/verify')).d;
check('DELETED entry detected', v3.ok === false && v3.brokenAt === 20, JSON.stringify(v3));

await srv.stop();
await disconnect();
finish();
