import { check, section, connect, disconnect, startServer, finish, makeAdmin, tokenFor, client } from '../lib.mjs';
import User from '../../src/models/User.js';
import Loan from '../../src/models/Loan.js';
import AuditLog from '../../src/models/AuditLog.js';
import { analyse, sampleStatement } from '../../src/services/aaService.js';
import { DEFAULTS, evaluate, validateRules, gatherFacts, SUGGESTED_START } from '../../src/services/decisionEngine.js';

section('READING STATEMENTS');
const salaried = analyse(sampleStatement('salaried', 40000).transactions);
check('six months are seen', salaried.months === 6 && salaried.entries > 20, JSON.stringify(salaried));
check('the salary is found and the income is the salary', salaried.salaryDetected === true && salaried.estimatedMonthlyIncome === 40000 && salaried.incomeStabilityPercent === 100);
check('the home loan EMI is found as a repayment (25% of salary)', salaried.monthlyObligations === 10000);
check('no bounces on the clean statements', salaried.bounces === 0);
const stressed = analyse(sampleStatement('stressed', 40000).transactions);
check('bounced payments are counted', stressed.bounces === 9, String(stressed.bounces));
check('a very low balance shows up', stressed.lowBalancePercent > 0 && stressed.minBalance <= 1000);
const irregular = analyse(sampleStatement('irregular', 40000).transactions);
check('irregular money in is not called a salary', irregular.salaryDetected === false && irregular.estimatedMonthlyIncome === null && irregular.avgMonthlyCredits > 0);
check('nothing readable gives nothing', analyse([]) === null && analyse([{ date: 'x', amount: 5, type: 'CREDIT' }]) === null && analyse(null) === null);
const unnamed = analyse(Array.from({ length: 6 }, (_, i) => ({ date: new Date(Date.UTC(2026, i, 3 + i)).toISOString(), amount: 52000 + i * 300, type: 'CREDIT', narration: 'NEFT FROM ACME' })));
check('a steady monthly credit of about the same size counts as salary even without the word', unnamed.salaryDetected === true && unnamed.estimatedMonthlyIncome > 51000);

section('THE RULE');
const base = { amount: 30000, age: 32, kycApproved: true, phoneVerified: true, openAmlAlerts: 0, defaultedLoans: 0, openLoans: 0, overdueEmis: 0, repeatCustomer: false, bureauScore: 720, selfieStatus: 'passed', monthlyIncome: 40000, declaredIncome: 40000, emi: 3500, applicationsRecent: 1, rejectionsRecent: 0, maxDaysLate: 0, accountAgeDays: 10, state: 'Maharashtra', pincode: '400012', incomeVerified: false, verifiedMonthlyIncome: 0, bankBounces: 0, bankObligations: 0 };
const on = o => ({ ...DEFAULTS, incomeCheck: { ...DEFAULTS.incomeCheck, enabled: true, ...o } });
const pick = (rules, f) => evaluate(rules, { ...base, ...f }).checks.find(c => c.code === 'INCOME');
check('off by default', pick(DEFAULTS, {}).result === 'skip');
check('on, nothing shared, nothing demanded: skipped with a note', pick(on({}), {}).result === 'skip' && /not shared/.test(pick(on({}), {}).detail));
check('on, a big loan with nothing shared: a person decides', pick(on({ requireAbove: 20000 }), {}).result === 'refer');
check('on, a small loan with nothing shared: still skipped', pick(on({ requireAbove: 50000 }), {}).result === 'skip');
const ok = { incomeVerified: true, verifiedMonthlyIncome: 40000 };
check('statements that support the income pass', pick(on({}), ok).result === 'pass');
check('too many bounces send it to a person', pick(on({ maxBounces: 2 }), { ...ok, bankBounces: 3 }).result === 'refer');
check('declared income far above the statements sends it to a person', pick(on({ maxDeclaredGapPercent: 30 }), { ...ok, verifiedMonthlyIncome: 25000, declaredIncome: 40000 }).result === 'refer');
check('a small gap is fine', pick(on({ maxDeclaredGapPercent: 30 }), { ...ok, verifiedMonthlyIncome: 35000, declaredIncome: 40000 }).result === 'pass');
check('a minimum income is enforced', pick(on({ minVerifiedIncome: 30000 }), { ...ok, verifiedMonthlyIncome: 20000, declaredIncome: 20000 }).result === 'refer');
check('repayments plus the new EMI as a share of income are limited', pick(on({ maxObligationShare: 50 }), { ...ok, emi: 8000, bankObligations: 15000 }).result === 'refer' && pick(on({ maxObligationShare: 50 }), { ...ok, emi: 3000, bankObligations: 5000 }).result === 'pass');
check('it never rejects by itself', !['reject'].includes(pick(on({ maxBounces: 0, minVerifiedIncome: 99999 }), { ...ok, bankBounces: 9 }).result));
check('test data is labelled', /test data/.test(pick(on({}), { ...ok, incomeCheckTest: true }).detail));
check('bad settings are refused', validateRules({ incomeCheck: { enabled: true, maxBounces: -1 } }).errors.length > 0 && validateRules({ incomeCheck: { enabled: true, maxObligationShare: 500 } }).errors.length > 0);
check('the suggested starting values are valid', validateRules({ ...DEFAULTS, ...SUGGESTED_START }).errors.length === 0);

const DB = 'fintech-test-income';
await connect(DB);
const srv = await startServer(DB);
const prod = await startServer(DB, { PAYMENT_MODE: 'PRODUCTION' });
const call = client(srv.base), callProd = client(prod.base);
const { token: admin } = await makeAdmin();
const user = await User.create({ firstName: 'Inc', lastName: 'Ome', email: 'inc@x.in', phone: '9500000777', password: 'x12345678', kycStatus: 'approved', employment: { status: 'Employed', monthlyIncome: 60000 } });
const tok = await tokenFor(user);
const form = (path, body) => fetch(srv.base + path, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams(body).toString(), redirect: 'manual' });

section('THE CUSTOMER JOURNEY (TEST MODE)');
const mine0 = await call('GET', '/income-check/mine', tok);
check('test mode is offered and nothing is shared yet', mine0.s === 200 && mine0.d.available && mine0.d.mode === 'sandbox' && mine0.d.check === null);
check('a stranger cannot start for someone else (needs login, 401)', (await call('POST', '/income-check/start', null)).s === 401);
const st = await call('POST', '/income-check/start', tok);
check('it starts and gives a link to the stand-in page', st.s === 200 && st.d.url.includes('/api/income-check/sandbox/') && st.d.mode === 'sandbox', JSON.stringify(st.d));
const sid = st.d.sessionId;
const pageGet = await fetch(srv.base + `/income-check/sandbox/${sid}`);
check('the stand-in page says it is a test', pageGet.status === 200 && (await pageGet.text()).includes('TEST MODE'));
check('before approval the status is waiting', (await call('GET', `/income-check/status/${sid}`, tok)).d.status === 'created');
const other = await tokenFor(await User.create({ firstName: 'O', lastName: 'T', email: 'ot@x.in', phone: '9500000778', password: 'x12345678' }));
check('someone else cannot read the session (404)', (await call('GET', `/income-check/status/${sid}`, other)).s === 404);
const done = await form(`/income-check/sandbox/${sid}`, { action: 'allow', profile: 'salaried', salary: '45000' });
check('approving redirects to the done page', done.status === 302 && /callback/.test(done.headers.get('location')));
const fin = await call('GET', `/income-check/status/${sid}`, tok);
check('the session completes with a summary', fin.d.status === 'completed' && fin.d.result.estimatedMonthlyIncome === 45000 && fin.d.result.mode === 'sandbox', JSON.stringify(fin.d));
const saved = await User.findById(user._id);
check('only a summary is kept on the customer (no transactions)', saved.incomeCheck.estimatedMonthlyIncome === 45000 && !('transactions' in saved.incomeCheck) && !JSON.stringify(saved.incomeCheck).includes('NEFT'));
check('the page cannot be used twice (404)', (await fetch(srv.base + `/income-check/sandbox/${sid}`)).status === 404);
check('the customer sees the result', (await call('GET', '/income-check/mine', tok)).d.check.salaryDetected === true);
check('staff see it on the customer', (await call('GET', `/admin/customers/${user._id}`, admin)).d.customer.incomeCheck.estimatedMonthlyIncome === 45000);
check('it is in the audit log', (await AuditLog.countDocuments({ action: 'INCOME_CHECK_DONE' })) === 1);

section('FACTS FOR THE DECISION');
const loan = await Loan.create({ userId: user._id, loanAmount: 30000, tenure: 6, interestRate: 15, monthlyEMI: 5300, status: 'submitted' });
const rulesOn = { ...DEFAULTS, incomeCheck: { ...DEFAULTS.incomeCheck, enabled: true } };
const facts = await gatherFacts(loan, saved, rulesOn);
check('the statements count, and the income used is the one in the statements', facts.incomeVerified && facts.verifiedMonthlyIncome === 45000 && facts.monthlyIncome === 45000 && facts.declaredIncome === 60000 && facts.incomeCheckTest === true, JSON.stringify(facts));
const keep = await gatherFacts(loan, saved, { ...rulesOn, incomeCheck: { ...rulesOn.incomeCheck, useVerifiedIncome: false } });
check('the lender can keep using the declared income', keep.monthlyIncome === 60000);
const off = await gatherFacts(loan, saved, DEFAULTS);
check('with the rule off the declared income is used', off.monthlyIncome === 60000);
await User.updateOne({ _id: user._id }, { 'incomeCheck.at': new Date(Date.now() - 100 * 864e5) });
check('a result older than 90 days no longer counts', (await gatherFacts(loan, await User.findById(user._id), rulesOn)).incomeVerified === false);

section('DECLINING, REMOVING, PRODUCTION');
const st2 = await call('POST', '/income-check/start', tok);
await form(`/income-check/sandbox/${st2.d.sessionId}`, { action: 'deny' });
check('declining leaves it failed and keeps nothing new', (await call('GET', `/income-check/status/${st2.d.sessionId}`, tok)).d.status === 'failed');
check('the customer can remove their summary', (await call('DELETE', '/income-check/mine', tok)).d.removed === true && (await call('GET', '/income-check/mine', tok)).d.check === null);
check('removing again says nothing was there', (await call('DELETE', '/income-check/mine', tok)).d.removed === false);
check('it is in the audit log', (await AuditLog.countDocuments({ action: 'INCOME_CHECK_WITHDRAWN' })) === 1);
const p = await tokenFor(await User.create({ firstName: 'P', lastName: 'R', email: 'pr@x.in', phone: '9500000779', password: 'x12345678' }));
const pm = await callProd('GET', '/income-check/mine', p);
check('in production with no provider it says not available', pm.d.available === false && pm.d.mode === 'unavailable');
check('and cannot be started (503)', (await callProd('POST', '/income-check/start', p)).s === 503);
check('the test page is not there (404)', (await fetch(prod.base + '/income-check/sandbox/64b000000000000000000000')).status === 404);

await disconnect();
finish();
