import http from 'http';
import { check, section, connect, disconnect, startServer, finish, makeAdmin, tokenFor, client, day } from '../lib.mjs';
import User from '../../src/models/User.js';
import Loan from '../../src/models/Loan.js';
import EMIPayment from '../../src/models/EMIPayment.js';
import Config from '../../src/models/Config.js';
import JobLock from '../../src/models/JobLock.js';
import SystemAlert from '../../src/models/SystemAlert.js';
import MetricBucket from '../../src/models/MetricBucket.js';
import PayoutRecord from '../../src/models/PayoutRecord.js';
import { mapLimit, cached } from '../../src/services/concurrency.js';
import { runLocked } from '../../src/services/jobRunner.js';
import { raiseAlert, resolveAlert } from '../../src/services/alerts.js';
import { check as monitorCheck } from '../../src/services/monitorService.js';
import { setConfig } from '../../src/services/configService.js';
import { buildQueue } from '../../src/services/collectionsService.js';
import { HOST } from '../../src/services/metrics.js';

const DB = 'fintech-test-scaling';
await connect(DB);
process.env.ALLOW_LOCAL_WEBHOOK = '1';

section('INDEXES THE SCREENS AND JOBS RELY ON');
await Loan.init(); await EMIPayment.init(); await User.init();
const names = async m => (await m.collection.indexes()).map(i => i.name);
const li = await names(Loan), ei = await names(EMIPayment), ui = await names(User);
check('loans: by customer and date', li.includes('userId_1_createdAt_-1'), li.join());
check('loans: by status and date', li.includes('status_1_createdAt_-1'));
check('EMIs: by status and due date', ei.includes('status_1_dueDate_1'));
check('customers: by sign-up date and by name', ui.includes('createdAt_-1') && ui.includes('firstName_1') && ui.includes('lastName_1'));

section('DOING MANY THINGS AT ONCE');
let running = 0, peak = 0;
const r = await mapLimit(Array.from({ length: 40 }, (_, i) => i), 5, async i => { running++; peak = Math.max(peak, running); await new Promise(res => setTimeout(res, 5)); running--; if (i === 7) throw new Error('one bad item'); return i; });
check('never more than 5 at the same time', peak <= 5 && peak > 1, `peak ${peak}`);
check('one failure is counted and the rest still finish', r.failed === 1 && r.results.filter(x => x !== undefined).length === 39);
let calls = 0;
const [c1, c2, c3] = await Promise.all([1, 2, 3].map(() => cached('k', 1000, async () => { calls++; await new Promise(res => setTimeout(res, 20)); return 'v'; })));
check('three staff opening the same page cost one calculation', calls === 1 && c1 === 'v' && c3 === 'v');

section('A JOB RUNS ONCE EVEN WITH SEVERAL SERVERS');
let ran = 0;
const slow = () => runLocked('t-job', 5000, async () => { ran++; await new Promise(res => setTimeout(res, 150)); return 'done'; });
const both = await Promise.all([slow(), slow(), slow()]);
check('three servers start it at once: it runs one time', ran === 1 && both.filter(x => x.ran).length === 1 && both.filter(x => x.skipped).length === 2, JSON.stringify(both));
const again = await slow();
check('afterwards it can run again', again.ran === true && ran === 2);
let told = null;
const failed = await runLocked('t-fail', 5000, async () => { throw new Error('boom'); }, { onFail: async (name, e) => { told = `${name}:${e.message}`; } });
const lock = await JobLock.findOne({ name: 't-fail' });
check('a failing job is recorded and reported, and does not crash', failed.error === 'boom' && told === 't-fail:boom' && lock.failures === 1 && lock.lastError === 'boom');
// A run longer than its lock time keeps the lock, so a second server cannot start the same job
let longRuns = 0;
const longJob = () => runLocked('t-long', 1500, async () => { longRuns++; await new Promise(res => setTimeout(res, 2600)); });
const l1 = longJob();
await new Promise(res => setTimeout(res, 2000));
const l2 = await longJob();
await l1;
check('a job that outlasts its lock time still cannot be started twice', longRuns === 1 && l2.skipped === true, `${longRuns} ${JSON.stringify(l2)}`);
await JobLock.updateOne({ name: 't-job' }, { holder: 'another-server', until: new Date(Date.now() + 60000) });
check('while another server holds the lock, this one stays out', (await slow()).skipped === true);
await JobLock.updateOne({ name: 't-job' }, { until: new Date(Date.now() - 1000) });
check('a lock left by a dead server expires on its own', (await slow()).ran === true);

section('SEVERAL SERVERS SHARE THE REQUEST LIMIT AND THE SETTINGS');
const A = await startServer(DB, { RATE_LIMIT_STORE: 'shared', API_RATE_LIMIT: '6', CONFIG_REFRESH_SECONDS: '1' });
const B = await startServer(DB, { RATE_LIMIT_STORE: 'shared', API_RATE_LIMIT: '6', CONFIG_REFRESH_SECONDS: '1' });
const ca = client(A.base), cb = client(B.base);
// Starting a server polls /health, and those requests count against the shared limit: start from zero
await (await import('mongoose')).default.connection.collection('ratelimits').deleteMany({});
const codes = [];
for (let i = 0; i < 4; i++) codes.push((await ca('GET', '/pricing')).s);
for (let i = 0; i < 4; i++) codes.push((await cb('GET', '/pricing')).s);
check('6 requests allowed across both servers, then refused (429)', codes.filter(c => c === 200).length === 6 && codes.filter(c => c === 429).length === 2, codes.join());
A.stop(); B.stop();

const A2 = await startServer(DB, { CONFIG_REFRESH_SECONDS: '1' });
const B2 = await startServer(DB, { CONFIG_REFRESH_SECONDS: '1' });
const cb2 = client(B2.base);
check('before the change, server B shows no banner', (await cb2('GET', '/app-settings')).d.banner?.enabled === false);
await Config.findOneAndUpdate({ key: 'APP_SETTINGS' }, { key: 'APP_SETTINGS', value: JSON.stringify({ banner: { enabled: true, level: 'info', text: 'Hello from server A' } }), group: 'app' }, { upsert: true });
await new Promise(res => setTimeout(res, 2500));
check('a setting changed elsewhere reaches server B within seconds', (await cb2('GET', '/app-settings')).d.banner?.text === 'Hello from server A');
A2.stop(); B2.stop();

section('SEVERAL PROCESSES FROM ONE START');
const W = await startServer(DB, { WEB_CONCURRENCY: '2' });
const admin = await makeAdmin();
const cw = client(W.base);
const sys0 = await cw('GET', '/admin/system', admin.token);
check('starts with 2 processes and answers', sys0.s === 200 && sys0.d.process.processes === 2);
check('the readiness check answers 200', (await cw('GET', '/health/ready')).s === 200);
const rid = await fetch(`${W.base}/health`, { headers: { 'x-request-id': 'abc-123' } });
check('every response carries a request id, and one sent in is kept', rid.headers.get('x-request-id') === 'abc-123');
check('a request without one gets one', !!(await fetch(`${W.base}/health`)).headers.get('x-request-id'));
W.stop();

section('A DUE-TODAY EMI IS NOT YET A COLLECTIONS CASE');
const u = await User.create({ firstName: 'Late', lastName: 'Today', email: 'late@x.in', phone: '9600000001', password: 'x12345678' });
const l = await Loan.create({ userId: u._id, loanAmount: 10000, tenure: 3, status: 'disbursed', monthlyEMI: 3500, disbursementDate: day(-30) });
await EMIPayment.create({ loanId: l._id, userId: u._id, emiNumber: 1, dueDate: new Date(Date.now() - 3 * 3600 * 1000), amount: 3500, principalAmount: 3300, interestAmount: 200, status: 'PENDING' });
check('the queue skips it instead of failing', (await buildQueue()).length === 0);
await EMIPayment.updateOne({ loanId: l._id }, { dueDate: day(-3) });
const q = await buildQueue();
check('three days late it is a case, found from the EMI side', q.length === 1 && q[0].stage === 'REMINDER' && q[0].daysOverdue === 3);

section('ALERTS REACH PEOPLE');
const got = [];
const hook = http.createServer((req, res) => { let b = ''; req.on('data', d => { b += d; }); req.on('end', () => { got.push(JSON.parse(b).text); res.end('ok'); }); });
await new Promise(res => hook.listen(0, res));
await setConfig('ALERT_WEBHOOK_URL', `http://localhost:${hook.address().port}/x`, { group: 'alerts' });
const a1 = await raiseAlert({ key: 'k1', severity: 'critical', title: 'Something broke', detail: 'details here' });
check('an alert is delivered to the chat address', got.length === 1 && /Something broke/.test(got[0]) && /CRITICAL/.test(got[0]) && a1.notified.includes('webhook'));
await raiseAlert({ key: 'k1', severity: 'critical', title: 'Something broke' });
check('the same problem is not repeated within the hour', got.length === 1 && (await SystemAlert.findOne({ key: 'k1' })).count === 2);
await resolveAlert('k1');
await raiseAlert({ key: 'k1', severity: 'critical', title: 'Something broke' });
check('a problem that comes back after being resolved is announced again', got.length === 2);
await SystemAlert.deleteMany({});

section('THE CHECKS NOTICE REAL PROBLEMS');
const now = Math.floor(Date.now() / 60000);
await MetricBucket.deleteMany({});
const quiet = await monitorCheck();
check('a quiet, healthy system raises nothing', quiet.problems.length === 0 && (await SystemAlert.countDocuments({ status: 'open' })) === 0, JSON.stringify(quiet));
await MetricBucket.create({ _id: `${HOST}-${now}`, host: HOST, minute: new Date(now * 60000), n: 100, e4: 0, e5: 40, sumMs: 5000, h: [60, 0, 0, 0, 0, 0, 40] });
const bad = await monitorCheck();
const errA = await SystemAlert.findOne({ key: 'errors-high' });
check('40 server errors in 100 requests opens a critical alert and tells the team', bad.problems.includes('traffic') && errA?.status === 'open' && errA.severity === 'critical' && got.some(t => /Many requests are failing/.test(t)));
check('slow responses are noticed too', (await SystemAlert.findOne({ key: 'slow' }))?.status === 'open');
await MetricBucket.deleteMany({});
await monitorCheck();
check('when traffic is healthy again the alerts close by themselves', (await SystemAlert.findOne({ key: 'errors-high' })).status === 'resolved' && (await SystemAlert.findOne({ key: 'slow' })).status === 'resolved');
await JobLock.create({ name: 'auto-payouts', holder: 'x', until: new Date(), lastFinishedAt: new Date(Date.now() - 2 * 86400000), runs: 5 });
const stale = await monitorCheck();
check('a job that stopped running is noticed', stale.problems.includes('job auto-payouts') && (await SystemAlert.findOne({ key: 'job-stale:auto-payouts' }))?.status === 'open');
await JobLock.updateOne({ name: 'auto-payouts' }, { lastFinishedAt: new Date() });
await monitorCheck();
check('and clears when it runs again', (await SystemAlert.findOne({ key: 'job-stale:auto-payouts' })).status === 'resolved');
await PayoutRecord.create({ kind: 'referral', targetId: u._id, amount: 100, referenceId: 'R-1', provider: 'sandbox', status: 'failed', failureReason: 'bank rejected', finishedAt: new Date() });
await monitorCheck();
check('a failed payout opens a warning', (await SystemAlert.findOne({ key: 'payouts-failed' }))?.status === 'open');

section('THE SYSTEM HEALTH PAGE');
const S = await startServer(DB);
const cs = client(S.base);
const sys = await cs('GET', '/admin/system', admin.token);
check('staff can see database, traffic, jobs and alerts', sys.s === 200 && sys.d.database.ok && Array.isArray(sys.d.jobs) && sys.d.jobs.length >= 8 && Array.isArray(sys.d.alerts.open) && sys.d.traffic.minutes === 60, JSON.stringify(Object.keys(sys.d)));
check('it says whether alerts can reach anyone', sys.d.notify.reachable === true);
const cust = await tokenFor(u);
check('customers cannot open it', [401, 403].includes((await cs('GET', '/admin/system', cust)).s));
check('a bad email is refused (400)', (await cs('PUT', '/admin/system/notify', admin.token, { emails: 'not-an-email' })).s === 400);
check('a web address that is not https is refused (400)', (await cs('PUT', '/admin/system/notify', admin.token, { webhook: 'http://example.com/x' })).s === 400);
check('the repeat time must be sensible (400)', (await cs('PUT', '/admin/system/notify', admin.token, { repeatMinutes: 1 })).s === 400);
check('good settings are saved', (await cs('PUT', '/admin/system/notify', admin.token, { emails: 'ops@lifc.in, tech@lifc.in', webhook: `http://localhost:${hook.address().port}/x`, repeatMinutes: 30 })).s === 200);
const test = await cs('POST', '/admin/system/test-alert', admin.token, {});
check('a test alert is delivered and does not stay open', test.s === 200 && test.d.notified.includes('webhook') && got.some(t => /Test alert/.test(t)) && (await SystemAlert.countDocuments({ key: /^test:/, status: 'open' })) === 0, JSON.stringify(test.d));
S.stop();
hook.close();

await disconnect();
finish();
